---
- name: Install Docker prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - make
    state: present
  become: true
  delegate_to: localhost

- name: Ensure 'unzip' is installed
  ansible.builtin.apt:
    name: unzip
    state: present
  become: true
  delegate_to: localhost

- name: Install Python and pip
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present
  become: true
  delegate_to: localhost

- name: Install pywinrm
  ansible.builtin.pip:
    name: pywinrm
    state: present
    extra_args: --break-system-packages
  become: true
  delegate_to: localhost

- name: Set Terraform version
  ansible.builtin.set_fact:
    utility_terraform_version: '1.7.5'
  delegate_to: localhost

- name: Download Terraform
  ansible.builtin.unarchive:
    src: 'https://releases.hashicorp.com/terraform/{{ utility_terraform_version }}/terraform_{{ utility_terraform_version }}_linux_amd64.zip'
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/terraform
  become: true
  delegate_to: localhost

- name: Install talosctl
  ansible.builtin.get_url:
    url: https://talos.dev/install
    dest: /tmp/talos_install.sh
    mode: '0755'
  become: true
  delegate_to: localhost

- name: Execute talosctl install script
  ansible.builtin.command:
    cmd: /tmp/talos_install.sh
  args:
    creates: /usr/local/bin/talosctl
  become: true
  delegate_to: localhost

- name: Get kubectl stable version
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: true
  register: utility_kubectl_version
  delegate_to: localhost

- name: Download kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ utility_kubectl_version.content | trim }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
  become: true
  delegate_to: localhost
  changed_when: false

- name: Set k9s version
  ansible.builtin.set_fact:
    utility_k9s_version: '0.28.2'
  delegate_to: localhost

- name: Download k9s
  ansible.builtin.unarchive:
    src: 'https://github.com/derailed/k9s/releases/download/v{{ utility_k9s_version }}/k9s_Linux_amd64.tar.gz'
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/k9s
  become: true
  delegate_to: localhost

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  delegate_to: localhost

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true
  delegate_to: localhost

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true
  delegate_to: localhost

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true
  delegate_to: localhost
