---
- name: Execute full terraform apply for Talos cluster provisioning
  ansible.builtin.command: "terraform apply -auto-approve -var-file=cluster.tfvars"
  args:
    chdir: "{{ terraform_dir }}"
  register: tf_talos_provisioning_output
  delegate_to: localhost

- name: Get raw kubeconfig from Terraform output
  ansible.builtin.command: "terraform output -raw kubeconfig"
  args:
    chdir: "{{ terraform_dir }}"
  register: raw_kubeconfig_output
  delegate_to: localhost

- name: Save raw kubeconfig to file
  ansible.builtin.copy:
    content: "{{ raw_kubeconfig_output.stdout }}"
    dest: "{{ terraform_dir }}/kubeconfig"
  delegate_to: localhost

- name: Notify user that Talos cluster is provisioned and healthy
  ansible.builtin.debug:
    msg: "Talos cluster is provisioned and healthy."
  delegate_to: localhost