machine:
  type: worker
  sysctls:
    vm.nr_hugepages: "1024"
  kernel:
    modules:
      - name: nvme_tcp
      - name: vfio_pci
  kubelet:
    extraMounts:
      - destination: /var/mnt/longhorn
        type: bind
        source: /var/mnt/longhorn
        options:
          - bind
          - rshared
          - rw
  network:
    hostname: ${hostname}
    interfaces:
      - deviceSelector:
          physical: true
        addresses: [${ip_addr}/24]
  install:
    disk: /dev/sda
    image: ${talos_installer}
  time:
    servers:
      - ${ntp_server}
  registries:
    mirrors:
      docker.io:
        endpoints:
          - ${registry_mirror_endpoint}
      gcr.io:
        endpoints:
          - ${registry_mirror_endpoint}
      ghcr.io:
        endpoints:
          - ${registry_mirror_endpoint}
      registry.k8s.io:
        endpoints:
          - ${registry_mirror_endpoint}
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn # becomes /var/mnt/longhorn on the host
provisioning:
  minSize: 1GiB
  diskSelector:
    match: disk.dev_path == "/dev/sdb"
  grow: true # use 100 % of the disk
filesystem:
  type: xfs