---
- name: Ensure 'unzip' is installed
  ansible.builtin.apt:
    name: unzip
    state: present
  become: true
  delegate_to: localhost

- name: Install Python and pip
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present
  become: true
  delegate_to: localhost

- name: Install pywinrm
  ansible.builtin.pip:
    name: pywinrm
    state: present
  become: true
  delegate_to: localhost

- name: Set Terraform version
  ansible.builtin.set_fact:
    terraform_version: '1.7.5'
  delegate_to: localhost

- name: Download Terraform
  ansible.builtin.unarchive:
    src: 'https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip'
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/terraform
  become: true
  delegate_to: localhost

- name: Set talosctl version
  ansible.builtin.set_fact:
    talosctl_version: '1.11.2'
  delegate_to: localhost

- name: Download talosctl
  ansansible.builtin.get_url:
    url: 'https://factory.talos.dev/talosctl/v{{ talosctl_version }}/talosctl-linux-arm64'
    dest: /usr/local/bin/talosctl
    mode: '0755'
    force: true
  become: true
  delegate_to: localhost
