---
- name: Execute terraform apply for hyperv-host module
  ansible.builtin.command: "terraform apply -target=module.host1 -auto-approve -var-file=cluster.tfvars"
  args:
    chdir: "{{ terraform_dir }}"
  register: tf_vm_creation_output
  delegate_to: localhost

- name: Read VM names and IPs from cluster.tfvars
  ansible.builtin.set_fact:
    host_vms: "{{ lookup('file', '{{ playbook_dir }}/../terraform/cluster.tfvars') | regex_findall('name = \"(.*?)\", role = \".*?\", ip = \"(.*?)\"', multiline=True) }}"
  delegate_to: localhost

- name: Verify VMs are running on Hyper-V host
  ansible.windows.win_shell: |
    $vm_names = @(
      {% for vm in host_vms %}
      "{{ vm.0 }}"{% if not loop.last %},{% endif %}
      {% endfor %}
    )
    $all_vms_running = $true
    foreach ($vm_name in $vm_names) {
        $vm_state = (Get-VM -Name $vm_name).State
        if ($vm_state -ne "Running") {
            Write-Host "VM $vm_name is not running. Current state: $vm_state"
            $all_vms_running = $false
        } else {
            Write-Host "VM $vm_name is running."
        }
    }
    if (-not $all_vms_running) {
        exit 1
    }
  register: vm_status_check
  until: vm_status_check.rc == 0
  retries: 30
  delay: 10

- name: Prompt user to verify/configure VM IPs
  ansible.builtin.pause:
    prompt: |
      ================================================================================
      PHASE 2: VIRTUAL MACHINE CREATION - IP VERIFICATION

      All virtual machines have been created and are running.
      Please verify that the VMs have been assigned the correct IP addresses
      as defined in 'terraform/cluster.tfvars'.

      If necessary, manually configure the static IP addresses for each VM.

      VMs and Expected IPs:
      {% for vm_name, vm_ip in host_vms %}
      - {{ vm_name }}: {{ vm_ip }}
      {% endfor %}

      Once you have verified/configured the IPs, type 'yes' to continue.
      ================================================================================
    echo: yes
  delegate_to: localhost

- name: Notify user that all VMs are created and running
  ansible.builtin.debug:
    msg: "All virtual machines are created and running on the Hyper-V host."
  delegate_to: localhost