name: Lint and Validate Infrastructure Code

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Install Ansible
        run: pip install ansible-lint ansible

      - name: Ansible Lint
        run: ansible-lint ansible/playbook.yml

      - name: Fail if Terraform fmt or validate failed
        if: steps.fmt.outcome == 'failure' || steps.validate.outcome == 'failure'
        run: |
          echo "Terraform formatting or validation failed!"
          exit 1
      
      - name: Run Ansible Playbook
        run: make init