name: Talos Hyper-V Cluster Provision

on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip sshpass
          pip3 install ansible pywinrm

      - name: Generate Ansible inventory
        run: |
          cat <<EOF > ansible/inventory.yml
          all:
            children:
              controller:
                hosts:
                  controller1:
                    ansible_host: "${{ secrets.CONTROLLER_HOST }}"
                    ansible_user: "${{ secrets.CONTROLLER_USER }}"
                    ansible_ssh_private_key_file: "${{ secrets.CONTROLLER_SSH_KEY_PATH }}"
                    tf_dir: "${{ secrets.TF_DIR }}"
              hyperv_hosts:
                hosts:
                  hyperv1:
                    ansible_host: "${{ secrets.HYPERV1_HOST }}"
                    ansible_user: "${{ secrets.HYPERV1_USER }}"
                    ansible_password: "${{ secrets.HYPERV1_PASS }}"
                  hyperv2:
                    ansible_host: "${{ secrets.HYPERV2_HOST }}"
                    ansible_user: "${{ secrets.HYPERV2_USER }}"
                    ansible_password: "${{ secrets.HYPERV2_PASS }}"
          EOF

      - name: Run Ansible Prepare ISO
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: ansible/playbooks/prepare_iso.yml
          inventory: ansible/inventory.yml
          key: ${{ secrets.CONTROLLER_SSH_PRIVATE_KEY }}

      - name: Run Ansible Provision Cluster
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: ansible/playbooks/provision_cluster.yml
          inventory: ansible/inventory.yml
          key: ${{ secrets.CONTROLLER_SSH_PRIVATE_KEY }}
          options: |
            --extra-vars "ip_range_start=${{ secrets.IP_RANGE_START }}
                          ip_range_end=${{ secrets.IP_RANGE_END }}
                          cp_count=${{ secrets.CP_COUNT }}
                          wk_count=${{ secrets.WK_COUNT }}
                          vm_prefix=${{ secrets.VM_PREFIX }}
                          iso_path=${{ secrets.TALOS_ISO_PATH }}
                          switch=${{ secrets.HYPERV_SWITCH }}
                          api_vip=${{ secrets.API_VIP }}""
